"""Jokes Table added Model

Revision ID: d9f426e877c3
Revises: 
Create Date: 2019-05-16 01:09:41.357665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f426e877c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('joke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_type', sa.String(length=80), nullable=False),
    sa.Column('setup', sa.String(length=255), nullable=False),
    sa.Column('punchline', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('joke')
    # ### end Alembic commands ###
